name: base-job-with-extends

on:
  workflow_call:
    inputs:
      EXAMPLE_ENV:
        type: string
        default: "Development"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: base-job
      run: |
        echo "This job will be run with EXAMPLE_ENV=$EXAMPLE_ENV"
