# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  simple-run:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: "3.9"
    - name: simple-run
      run: |
        echo "This job just run simple-app.py"
        python simple-app.py
    - name: print-file-content
      run: |
        echo "This job run simple-app.py with argument which will print file content"
        python simple-app.py simple-app/test.txt
