name: simple-app

on: push

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Download source code from repository
      uses: actions/checkout@v4.1.0
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4.7.0
      with:
        python-version: "3.10"
      
    - name: write-files
      run: |
        echo "Current working directory is $(pwd)"
        echo "Lets run simple-app.py to view directory content"
        python simple-app.py
        echo "Lets run writer.py to create two new files"
        python writer.py
        echo "Lets check directory content again and see two new files"
        python simple-app.py
        echo "We can also print content of this files"
        python simple-app.py test1.txt test2.txt

  post-main:
    runs-on: ubuntu-latest
    needs: main
    steps:
    - name: Download source code from repository
      uses: actions/checkout@v4.1.0
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4.7.0
      with:
        python-version: "3.10"
      
    - name: simple-app
      run: |
        echo "Lets run simple-app.py and see that in THIS job there are NO new files"
        python simple-app.py
